<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="QRCoder" />
        <PackageReference Include="SixLabors.Fonts" />
        <PackageReference Include="SixLabors.ImageSharp" />
        <PackageReference Include="SixLabors.ImageSharp.Drawing" />
        <PackageReference Include="System.CommandLine" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="output\" />
    </ItemGroup>

</Project>
