name: Publish to NuGet

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Get latest .NET SDK
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          dotnet-version: '10.0.x'

      - name: Pack
        run: dotnet pack src/WiFiQRCodeGenerator/WiFiQRCodeGenerator.csproj -c Release

      - name: Push to NuGet
        env:
          NUGET_TOKEN: ${{ secrets.TOKEN }}
        run: dotnet nuget push src/WiFiQRCodeGenerator/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key $NUGET_TOKEN
    permissions:
      id-token: write
      contents: read